### ISSUE TITLE
Getting a socketio client connection to receive a “signal only works in main thread” error

### ISSUE THREAD

**Issue by razenization** [miguelgrinberg/python-socketio#439] opened 2020-03-06 11:06 UTC
So, I am trying to make my django app automatically connect to socketio client when some conditions happen and parse data from it in order to thereafter send it to my own web socket and show on web page. When I'm using this code:

**views.py**

    def match(request, match_id):
        match = get_object_or_404(Match, pk=match_id)
        context = {'match': match}
        if match.is_live:
            livescore = Livescore(match.match_id, ).socket()
            context.setdefault('livescore', livescore)
        return render(request, 'myapp/match.html', context)`

to create **Livescore** class object:

    class Livescore:
        def __init__(
            self, list_id=None, scoreboard_callback=None, event_callback=None
    ):
            self.list_id = list_id
            self.sb_callback = scoreboard_callback
            self.event_callback = event_callback`

    def socket(self):
        sio = socketio.Client()

        @sio.event
        def connect():
            print("connection established")
            ready_data = {"listId": self.list_id}

            sio.emit("readyForMatch", json.dumps(ready_data))

        @sio.event
        def log(data):
            # do stuff

        @sio.event
        def event(data):
            # do stuff

        @sio.event
        def disconnect():
            print("disconnected from server")

        sio.connect("<websocket URI im trying to connect to for data parsing>")

        return sio

    
and parse info with callbacks, I receive this error:

> ValueError: signal only works in main thread

After I figure out this problem (if I do) I want to put this code into my django-cron class which will every time check whether the condition has been fulfilled, connect to socketio and store its instance somewhere else to operate with info I'm receiving and put it into my own web socket.

Is there any way I can resolve this error I'm getting and run socket.io at the background to send the data i receive to my own websocket via callback function?

**Comment by razenization** [comment] 2020-03-06 11:17
Traceback: 
`File "/opt/anaconda3/envs/ollo/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/ollo/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/ollo/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mysak/github/ollo/ollo_cs/views.py", line 30, in match
    livescore = SocketLivescore(match.match_id, )
  File "/Users/mysak/github/ollo/service.py", line 13, in __init__
    self.livescore = Livescore(self.match_id, self.sb_callb, self.event_callb).socket()
  File "/Users/mysak/github/ollo/ollo_cs/parse/live/livescore.py", line 63, in socket
    sio = socketio.Client()
  File "/opt/anaconda3/envs/ollo/lib/python3.7/site-packages/socketio/client.py", line 97, in __init__
    self.eio = self._engineio_client_class()(**engineio_options)
  File "/opt/anaconda3/envs/ollo/lib/python3.7/site-packages/engineio/client.py", line 82, in __init__
    signal_handler)
  File "/opt/anaconda3/envs/ollo/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
`

**Comment by miguelgrinberg** [comment] 2020-03-06 17:18
There is a fix for this in the master branch, did not get into a release yet. Can I ask you to try installing master from git and confirm the problem is gone?

**Comment by razenization** [comment] 2020-03-06 17:53
@miguelgrinberg downloaded the release from master but the problem didn't seem to go away. Still receiving the same message. Should I provide you with more information about how do I use it?

Basically, my main goal is to make this socket's data parse run in an asynchronous way, but for now I was trying to load it straight from **views.py**. Every time I'm trying to connect to a socket from anywhere instead of launching a .py file manually I'm receiving this error. Therefore, when I run some .py script which contains .socket() method it all works good.

**Comment by miguelgrinberg** [comment] 2020-03-06 23:32
I just realize that I should have also asked you to install the python-engineio dependency from its master branch, as the fix covers both packages. Sorry, can you install master from https://github.com/miguelgrinberg/python-engineio and try it one more time?

**Comment by VeNoMouS** [comment] 2020-03-07 00:57
Came here cause I got the same issue

**Comment by VeNoMouS** [comment] 2020-03-07 01:01
Downloaded the latest masters as stated... problem still exists..

**Comment by VeNoMouS** [comment] 2020-03-07 01:07
NM... it installed to another dir, so uninstalled from both paths... and installed master branch... issue is resolved.

Any eta when this will be pushed to pypi?

**Comment by razenization** [comment] 2020-03-07 08:04
Installed engine.io master and looks like the problem has gone away. Will keep you updated. Thank you.

**Comment by londomloto** [comment] 2020-03-23 07:57
the order of import matter:
`from django.core.wsgi import get_wsgi_application
import socketio`

**Closed** 2020-03-23 09:49 UTC
Labels: question
