### ISSUE TITLE
How to fix Error in connect  engineio_path=socketio_path

### ISSUE THREAD

**Issue by pecual** [miguelgrinberg/python-socketio#540] opened 2020-08-31 12:23 UTC
We have a plain python code:

```python
ListenPort = "http://180.13.1.245:3013"
sio = socketio.AsyncClient()
loop = asyncio.get_event_loop()
start_timer = None


async def send_ping():
    global start_timer
    start_timer = time.time()
    await sio.emit('ping_from_client')


@sio.event
async def connect():
    print('connected to server')
    await send_ping()


@sio.event
async def pong_from_server():
    global start_timer
    latency = time.time() - start_timer
    print('latency is {0:.2f} ms'.format(latency * 1000))
    await sio.sleep(1)
    await send_ping()


async def start_server():
    await sio.connect(ListenPort)
    #await sio.emit('report-client-register', {'token': sToken, 'channelRole': 'client'})
    #data = sio.call('push-broadcast-register')
    #print(data)


if __name__ == '__main__':
    #loop.run_until_complete(start_server())
    asyncio.run(start_server())
    ##loop.close()
```

```
Traceback (most recent call last):

  File "C:/00_Alberto/01_ATM_monitoring/04_Projects/Listener/main.py", line 73, in <module>
    asyncio.run(start_server())
  File "C:\Users\x222381\Anaconda3_\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\x222381\Anaconda3_\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "C:/00_Alberto/01_ATM_monitoring/04_Projects/Listener/main.py", line 65, in start_server
    await sio.connect(ListenPort)
  File "C:\Users\x222381\Anaconda3_\lib\site-packages\socketio\asyncio_client.py", line 111, in connect
    engineio_path=socketio_path)
  File "C:\Users\x222381\Anaconda3_\lib\site-packages\engineio\asyncio_client.py", line 87, in connect
    async_signal_handler)
  File "C:\Users\x222381\Anaconda3_\lib\asyncio\events.py", line 540, in add_signal_handler
    raise NotImplementedError
NotImplementedError

Process finished with exit code 1
```

Log File:

```
08/31/2020 02:20:15 PM Starting new HTTPS connection (1): cajeros.frontusuarios_st.monitorizacion.santander.pre.corp:443
08/31/2020 02:20:15 PM https://cajeros.frontusuarios_st.monitorizacion.santander.pre.corp:443 "POST /r/api/data/v1/login HTTP/1.1" 200 190
08/31/2020 02:20:15 PM Using selector: SelectSelector
```

**Comment by miguelgrinberg** [comment] 2020-08-31 13:49
This appears to happen only on Windows, due to not having a signal implementation for asyncio. It has already been reported, so I'm going to close as a duplicate of https://github.com/miguelgrinberg/python-socketio/issues/538.

**Closed by miguelgrinberg** 2020-08-31 13:49 UTC

**Comment by DovaX** [comment] 2020-09-03 09:01
Hi, I got the same error. It helped me to get back to version python-engineio-3.13.1
