### ISSUE TITLE
'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by higrw123** [miguelgrinberg/python-socketio#429] opened 2020-02-13 13:34 UTC
when i use client connected , then i close socket server , 
     await sio.wait() -> await self.eio.wait() -> async def _read_loop_websocket(self): ->   pkt = packet.Packet(encoded_packet=p)
will raise Exception
     'int' object has no attribute 'encode'
will break the logic of reconnect

**Comment by miguelgrinberg** [comment] 2020-02-13 20:39
This is a duplicate of https://github.com/miguelgrinberg/python-socketio/issues/417. Do you have a client and server I can use to reproduce this problem?

**Comment by higrw123** [comment] 2020-02-14 02:31
don't find your email,  can you give me one

**Comment by miguelgrinberg** [comment] 2020-02-14 21:53
first name dot last name at gmail

**Comment by miguelgrinberg** [comment] 2020-03-10 23:57
closing since this is a duplicate.

**Closed by miguelgrinberg** 2020-03-10 23:57 UTC
