### ISSUE TITLE
Error on connect: "connect_error() takes 0 positional arguments but 1 was given"

### ISSUE THREAD

**Issue by patrickcusack** [miguelgrinberg/python-socketio#581] opened 2020-12-10 19:35 UTC
I am attaching the output of my "pip3 freeze" as I am experiencing an error on connecting to my flask-socketio server. I encounter the following error:

"connect_error() takes 0 positional arguments but 1 was given" when attempting to connect. I do not see any errors server or client side to indicate what is causing the failure. I have several systems I have installed this on, and curiously I can not pinpoint the difference across system installs.

aiocontextvars==0.2.2
bidict==0.21.2
certifi==2020.12.5
chardet==3.0.4
contextvars==2.4
idna==2.10
immutables==0.14
loguru==0.5.3
psutil==5.7.3
python-engineio==4.0.0
python-socketio==5.0.1
requests==2.25.0
six==1.15.0
urllib3==1.26.2
websocket-client==0.57.0

**Comment by miguelgrinberg** [comment] 2020-12-10 19:51
Duplicate of https://github.com/miguelgrinberg/Flask-SocketIO/issues/1430. The problem is that you have not pinned your dependencies, you are pulling some that are incompatible with Flask-SocketIO. See the linked bug for a solution.

**Closed by miguelgrinberg** 2020-12-10 19:51 UTC
