### ISSUE TITLE
No disconnect event triggered after receiving no pong

### ISSUE THREAD

**Issue by Muzzamil1** [miguelgrinberg/python-socketio#326] opened 2019-08-01 08:36 UTC
Hi！
First of all thanks for the great library. I have a node.js server running socket.io and I use your socket.io client in raspberry pi. I am using the latest version i.e, 

- python == 3.7.3
- python-engineio == 3.9.0
- python-socketio == 4.3.0

Everything seems working great if I stop the server and then restart it python socket.io client reconnects.
**My code** 

```
import socketio
sio = socketio.Client(reconnection=True,
                      logger = True,
                      engineio_logger=True)
@sio.event
def connect():
    print('connected!!!')

@sio.event
def disconnect():
    print('disconnect!!!')

if __name__ == "__main__":
    sio.connect('https://domain:port/')
    sio.wait()
```

But if I disconnect the wifi it gives no pong warning.
**LOG**

> Attempting polling connection to https://domain:port/socket.io/?transport=polling&EIO=3
> Polling connection accepted with {'sid': 'EvWJiGehiqHiWaWsAAAJ', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
> Engine.IO connection established
> Received packet MESSAGE data 0
> Namespace / is connected
> Attempting WebSocket upgrade to wss://domain:port/socket.io/?transport=websocket&EIO=3
> connected!!!
> WebSocket upgrade was successful
> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> **_PONG response has not been received, aborting
> packet queue is empty, aborting
> Exiting write loop task_**

After that it just stuck there.No disconnect event occur .If I reconnect the wifi nothing happens it just stuck there until I press ctrl+c . After pressing it,disconnect event triggers 
**LOG**

> **_^CSending packet CLOSE data None
> Engine.IO connection dropped
> disconnect!!!_**
> Traceback (most recent call last):
>   File "pysocketIO.py", line 20, in <module>
>     id_socket.wait()
>   File "/usr/local/lib/python3.7/dist-packages/socketio/client.py", line 272, in wait
>     self.eio.wait()
>   File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 175, in wait
>     self.read_loop_task.join()
>   File "/usr/lib/python3.7/threading.py", line 1032, in join
>     self._wait_for_tstate_lock()
>   File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
>     elif lock.acquire(block, timeout):
>   File "/usr/local/lib/python3.7/dist-packages/socketio/client.py", line 25, in signal_handler
>     return original_signal_handler(sig, frame)
>   File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 41, in signal_handler
>     return original_signal_handler(sig, frame)
> KeyboardInterrupt
> ^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
>     t.join()
>   File "/usr/lib/python3.7/threading.py", line 1032, in join
>     self._wait_for_tstate_lock()
>   File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
>     elif lock.acquire(block, timeout):
>   File "/usr/local/lib/python3.7/dist-packages/socketio/client.py", line 25, in signal_handler
>     return original_signal_handler(sig, frame)
>   File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 41, in signal_handler
>     return original_signal_handler(sig, frame)
> KeyboardInterrupt

**Comment by miguelgrinberg** [comment] 2019-08-01 10:26
Are you disconnecting the wi-fi on the client, the server, or both?

**Comment by Muzzamil1** [comment] 2019-08-01 11:03
Appreciate the quick response.
Both but one at a time . If I stop the nodejs server then python socketio client triggers the disconnect event and when I restart the nodejs server, client reconnects the server automatically but if I disconnect wi-fi from any side client or server the python socketio client just stuck there with NO PONG message until I press the ctrl+c but nodejs socketio client reconnects the server if I disconnect wi-fi on server side or client side and disconnect event triggers on nodejs socketio client.

**Comment by miguelgrinberg** [comment] 2019-08-01 11:08
The network stack does not behave in the same way when you stop a process versus when you disable the network. My guess is that when you disable wi-fi the client is trying to write the PING and stays there trying for some time, until it will eventually time out. How long have you waited after you disabled the network?

**Comment by Muzzamil1** [comment] 2019-08-01 11:15
2-5 minutes .How long should I wait? In nodejs client case it show the server disconnection in less then one minute.

**Comment by miguelgrinberg** [comment] 2019-08-01 11:22
Okay, that's too long, should have happened in a minute or so. I'll try to reproduce the problem here.

**Comment by Muzzamil1** [comment] 2019-08-01 11:27
OK. 
Thanks for the quick response.

**Comment by miguelgrinberg** [comment] 2019-08-04 12:08
@Muzzamil1 I believe this is addressed by https://github.com/miguelgrinberg/python-engineio/issues/127, which I just fixed on the master branch of python-engineio. Can I ask you to install python-engineio master and retest?

**Comment by Muzzamil1** [comment] 2019-08-05 05:34
Yeah sure

**Comment by Muzzamil1** [comment] 2019-08-05 06:59
@miguelgrinberg I retested but the results were same.
Here is what I did.
Firstly, I uninstall both socketio and engineio. Then I reinstall python-socketio[client].
Now the versions are **python-engineio-3.9.2 python-socketio-4.3.0**.
After this I run the code and disable the wi-fi but got same results as before.
Then I install engineio with `sudo pip3 install https://github.com/miguelgrinberg/python-engineio/archive/master.zip`
Now the engineio version is **3.9.3dev**. It also gives the same result means no dis-connectivity event triggers and socket does not reconnect after enabling the wi-fi . I tested it from both side i.e, client and server by disconnecting the wi-fi.
Am I missing something?

**Comment by miguelgrinberg** [comment] 2019-08-05 07:33
@Muzzamil1 do you have new logs? The change I referenced adds a timeout to all requests, so I don't expect an outstanding request to hang forever anymore.

**Comment by Muzzamil1** [comment] 2019-08-05 07:46
### **Code**
```
import socketio
import engineio
print (socketio.__version__)
print (engineio.__version__)

sio = socketio.Client(reconnection=True,
                      logger = True,
                      engineio_logger=True)
@sio.event
def connect():
    print('connected!!!')

@sio.event
def disconnect():
    print('disconnect!!!')

if __name__ == "__main__":
    sio.connect('https://domain:port/')
```
### **Log**

> 4.3.0
> 3.9.3dev
> Attempting polling connection to https://domain:port/socket.io/?transport=polling&EIO=3
> Polling connection accepted with {'sid': 'eGmz3mimcBoKMn6tAAAf', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
> Engine.IO connection established
> Received packet MESSAGE data 0
> Namespace / is connected
> Attempting WebSocket upgrade to wss://domain:port/socket.io/?transport=websocket&EIO=3
> connected!!!
> WebSocket upgrade was successful
> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> PONG response has not been received, aborting
> packet queue is empty, aborting
> Exiting write loop task
### If I press **ctrl + c**

> ^CSending packet CLOSE data None
> Engine.IO connection dropped
> disconnect!!!
> Exception ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
>     t.join()
>   File "/usr/lib/python3.7/threading.py", line 1032, in join
>     self._wait_for_tstate_lock()
>   File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
>     elif lock.acquire(block, timeout):
>   File "/usr/local/lib/python3.7/dist-packages/socketio/client.py", line 25, in signal_handler
>     return original_signal_handler(sig, frame)
>   File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 41, in signal_handler
>     return original_signal_handler(sig, frame)
> KeyboardInterrupt

**Comment by Muzzamil1** [comment] 2019-08-05 07:56
It seems I am getting the old logs.

**Comment by miguelgrinberg** [comment] 2019-08-05 08:11
@Muzzamil1 can you reinstall python-engineio from master and try again please?

**Closed** 2019-08-05 08:11 UTC
Labels: bug

**Comment by Muzzamil1** [comment] 2019-08-05 08:42
### Log

> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> PONG response has not been received, aborting
> **Exiting ping task**
> Exiting write loop task

This time there is a new log but still no disconnect event occurs in client and after enabling the wi-fi it does not reconnect to server.

**Comment by miguelgrinberg** [comment] 2019-08-05 09:42
Unfortunately I cannot reproduce this here. In my case the connection is interrupted, and the client immediately attempts to reconnect. As soon as I turn wi-fi on again the connection is re-established. In all cases the connect and disconnect events were invoked as you can see in the output below:

```
(venv) $ python client.py
4.3.1dev
3.9.3dev
Attempting polling connection to http://example.com:5000/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'upgrades': ['websocket'], 'sid': 'd17e2d824ea5499da7ffb127be689807', 'pingInterval': 25000, 'pingTimeout': 60000}
Engine.IO connection established
Received packet MESSAGE data 2["my_response",{"data":"Connected","count":0}]
Received event "my_response" [/]
Received packet MESSAGE data 0
Namespace / is connected
connected!!!
Attempting WebSocket upgrade to ws://example.com:5000/socket.io/?transport=websocket&EIO=3
WebSocket upgrade was successful
Sending packet PING data None
Received packet NOOP data None
Received packet PONG data None
Sending packet PING data None
Received packet PONG data None

# here I turned wi-fi off

Sending packet PING data None
PONG response has not been received, aborting
Unexpected error "[Errno 9] Bad file descriptor", aborting
Waiting for write loop task to end
Exiting ping task
Exiting write loop task
Waiting for ping loop task to end
Engine.IO connection dropped
disconnect!!!
Connection failed, new attempt in 1.16 seconds
Exiting read loop task

# reconnect attempts start

Attempting polling connection to http://example.com:5000/socket.io/?transport=polling&EIO=3
HTTP GET request to http://example.com:5000/socket.io/?transport=polling&EIO=3&t=1564997669.214441 failed with error HTTPConnectionPool(host='example.com',
port=5000): Read timed out. (read timeout=5).
Connection failed, new attempt in 1.54 seconds
Attempting polling connection to http://example.com:5000/socket.io/?transport=polling&EIO=3
HTTP GET request to http://example.com:5000/socket.io/?transport=polling&EIO=3&t=1564997675.766895 failed with error HTTPConnectionPool(host='example.com',
port=5000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=3&t=1564997675.766895 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection objec
t at 0x1045c7240>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)).
Connection failed, new attempt in 4.08 seconds
Attempting polling connection to http://example.com:5000/socket.io/?transport=polling&EIO=3
HTTP GET request to http://example.com:5000/socket.io/?transport=polling&EIO=3&t=1564997679.8566349 failed with error HTTPConnectionPool(host='example.com',
 port=5000): Max retries exceeded with url: /socket.io/?transport=polling&EIO=3&t=1564997679.8566349 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection obj
ect at 0x1045c72b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)).
Connection failed, new attempt in 4.67 seconds

# here I turned wi-fi on again

Attempting polling connection to http://example.com:5000/socket.io/?transport=polling&EIO=3
Polling connection accepted with {'upgrades': ['websocket'], 'sid': 'd43c1a0cd7b646c38b5e47d33c3ecb3b', 'pingInterval': 25000, 'pingTimeout': 60000}
Engine.IO connection established
Received packet MESSAGE data 2["my_response",{"data":"Connected","count":0}]
Received event "my_response" [/]
Received packet MESSAGE data 0
Namespace / is connected
Attempting WebSocket upgrade to ws://example.com:5000/socket.io/?transport=websocket&EIO=3
connected!!!
WebSocket upgrade was successful
```

**Comment by Muzzamil1** [comment] 2019-08-05 10:20
@miguelgrinberg which OS are you using ? I just tested the same code in windows and it gives the similar results as yours but its not working in raspbian. You have any idea whats wrong with raspbian ?

**Comment by miguelgrinberg** [comment] 2019-08-05 10:23
@Muzzamil1 I used MacOS for the client in my test. Raspbian should be fairly similar to Ubuntu or other Debian distributions. I think I have an old Raspberry Pi somewhere, I'll look for it and retest, but in any case, this is looking more like an external problem, not sure how much more I'll be able to do.

**Comment by Muzzamil1** [comment] 2019-08-05 10:40
I tested it on Raspbian Buster and Raspbian Stretch. No problem I'll keep looking into this and update here if found anything. Please let me if you found something.
Thanks @miguelgrinberg. 
Great work.

**Comment by Muzzamil1** [comment] 2019-08-05 12:10
@miguelgrinberg  I just tested the asyncio example in Raspbian Buster and Raspbian Stretch and it worked perfectly.
### Code
```
import asyncio
import socketio
import engineio
print (socketio.__version__)
print (engineio.__version__)

loop = asyncio.get_event_loop()
sio = socketio.AsyncClient(reconnection=True,
                      logger = True,
                      engineio_logger=True)



@sio.event
async def connect():
    print('connected to server')

@sio.event
async def disconnect():
    print('disconnect !!!!!!!!!!!!!')


async def start_server():
    await sio.connect('https://domain:port/')
    await sio.wait()


if __name__ == '__main__':
    loop.run_until_complete(start_server())
```
### Log

> 4.3.0
> 3.9.3dev
> Attempting polling connection to https://domain:port/socket.io/?transport=polling&EIO=3
> Polling connection accepted with {'sid': 'cX7mmPNaQ7yJB7y1AAAr', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
> Engine.IO connection established
> Received packet MESSAGE data 0
> Attempting WebSocket upgrade to wss://domain:port/socket.io/?transport=websocket&EIO=3
> Namespace / is connected
> connected to server !!!!!!!!!!!!!
> WebSocket upgrade was successful
> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> 
> # here I turned wi-fi off
> 
> PONG response has not been received, aborting
> packet queue is empty, aborting
> Exiting write loop task
> Read loop: WebSocket connection was closed, aborting
> Waiting for write loop task to end
> Waiting for ping loop task to end
> Exiting ping task
> Engine.IO connection dropped
> disconnect !!!!!!!!!!!!!
> Exiting read loop task
> 
> # reconnect attempts start
> 
> Connection failed, new attempt in 0.79 seconds
> Attempting polling connection to https://domain:port/socket.io/?transport=polling&EIO=3
> HTTP GET request to https://domain:port/socket.io/?transport=polling&EIO=3&t=1565006001.8375084 failed with error Cannot connect to host domain:port ssl:None [Temporary failure in name resolution].
> Connection failed, new attempt in 1.62 seconds
> Attempting polling connection to https://domain:port/socket.io/?transport=polling&EIO=3
> HTTP GET request to https://domain:port/socket.io/?transport=polling&EIO=3&t=1565006003.4758031 failed with error Cannot connect to host domain:port ssl:None [Temporary failure in name resolution].
> Connection failed, new attempt in 3.99 seconds
> Attempting polling connection to https://domain:port/socket.io/?transport=polling&EIO=3
> HTTP GET request to https://domain:port/socket.io/?transport=polling&EIO=3&t=1565006007.481031 failed with error Cannot connect to host domain:port ssl:None [Temporary failure in name resolution].
> Connection failed, new attempt in 4.88 seconds
> Attempting polling connection to https://domain:port/socket.io/?transport=polling&EIO=3
> HTTP GET request to https://domain:port/socket.io/?transport=polling&EIO=3&t=1565006012.3832486 failed with error Cannot connect to host domain:port ssl:None [Temporary failure in name resolution].
> Connection failed, new attempt in 4.51 seconds
> Attempting polling connection to https://domain:port/socket.io/?transport=polling&EIO=3
> HTTP GET request to https://domain:port/socket.io/?transport=polling&EIO=3&t=1565006016.908624 failed with error Cannot connect to host domain:port ssl:None [Temporary failure in name resolution].
> Connection failed, new attempt in 5.08 seconds
> Attempting polling connection to https://domain:port/socket.io/?transport=polling&EIO=3
> Polling connection accepted with {'sid': 'YEvyY618kZnOIhiWAAAs', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
> 
> # reconnects
> 
> Engine.IO connection established
> Received packet MESSAGE data 0
> Attempting WebSocket upgrade to wss://domain:port/socket.io/?transport=websocket&EIO=3
> Namespace / is connected
> connected to server !!!!!!!!!!!!!
> WebSocket upgrade was successful
> Reconnection successful
> Sending packet PING data None
> Received packet PONG data None
> Sending packet PING data None
> Received packet PONG data None
