### ISSUE TITLE
Issue with Sanic v20.12.0 and python-socketio v5.0.4

### ISSUE THREAD

**Issue by Quantum-Sicarius** [miguelgrinberg/python-socketio#618] opened 2021-01-26 09:38 UTC
When using a combination of Sanic v20.12.0 and python-socketio v5.0.4 I get the following:
```
[2021-01-26 10:56:26 +0200] [19456] [ERROR] Exception occurred while handling uri: 'http://localhost:8000/socket.io/?EIO=4&transport=polling&t=NSzw8ge'
Traceback (most recent call last):
  File "/home/thomas/.local/lib/python3.9/site-packages/sanic/app.py", line 914, in handle_request
    response = await response
  File "/home/thomas/.local/lib/python3.9/site-packages/engineio/asyncio_server.py", line 308, in handle_request
    return await self._make_response(r, environ)
  File "/home/thomas/.local/lib/python3.9/site-packages/engineio/asyncio_server.py", line 376, in _make_response
    response = make_response(
  File "/home/thomas/.local/lib/python3.9/site-packages/engineio/async_drivers/sanic.py", line 102, in make_response
    return HTTPResponse(body_bytes=payload, content_type=content_type,
TypeError: __init__() got an unexpected keyword argument 'body_bytes'
```

This does however work normally with Sanic v19.12.3 and python-socketio v5.0.4

Is there a different method I should be using with v20 of Sanic?

**Comment by miguelgrinberg** [comment] 2021-01-26 10:04
Duplicate of https://github.com/miguelgrinberg/python-engineio/pull/207.

**Closed by miguelgrinberg** 2021-01-26 10:04 UTC
