### ISSUE TITLE
Client disconnect sometimes results in exceptions

### ISSUE THREAD

**Issue by VeNoMouS** [miguelgrinberg/python-socketio#498] opened 2020-05-31 23:58 UTC
Calling a disconnect sometimes results in the following exception, which you can't trap...

```
python-engineio==3.13.0
python-socketio==4.6.0
```

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 689, in _write_loop
    self.ws.send(encoded_packet)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 242, in send
    return self.send_frame(frame)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 267, in send_frame
    l = self._send(data)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 437, in _send
    return send(self.sock, data)
  File "/usr/lib/python3/dist-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
OSError: [Errno 9] Bad file descriptor
```

or 

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/engineio/client.py", line 689, in _write_loop
    self.ws.send(encoded_packet)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 242, in send
    return self.send_frame(frame)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 267, in send_frame
    l = self._send(data)
  File "/usr/lib/python3/dist-packages/websocket/_core.py", line 437, in _send
    return send(self.sock, data)
  File "/usr/lib/python3/dist-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by VeNoMouS** [comment] 2020-06-01 00:11
I see websocket-client is a requirement in `setup.py`

```
   extras_require={
        'client': [
            'requests>=2.21.0',
            'websocket-client>=0.54.0',
        ],
```

but it works without it, and i dont see reference to it in the code??

**Comment by miguelgrinberg** [comment] 2020-06-01 13:50
Thanks, I think I can handle these exceptions to prevent the crash.

**Comment by miguelgrinberg** [comment] 2020-06-01 13:52
Closing, duplicate of https://github.com/miguelgrinberg/python-engineio/issues/177.

**Closed by miguelgrinberg** 2020-06-01 13:52 UTC
Labels: bug
