### ISSUE TITLE
Provide a way to provide custom CA for websocket transport

### ISSUE THREAD

**Issue by hstejas** [miguelgrinberg/python-socketio#522] opened 2020-07-17 08:05 UTC
I have a custom CA chain which works with `requests` module and also when python-socketio is doing a https request with polling transport.
I just have to set an environment variable REQUESTS_CA_BUNDLE for this (Probably other ways with request also work)

the wss:// connections only work when I create a client with  `ssl_verify=False` but fails otherwise.
I could not find any way to prove a certificate though, I would be good to have this feature.

Also the error probably can be improved.  I only get this, and this is not helpful

```
INFO:engineio.client:Attempting WebSocket connection to wss://localhost/my/path/?transport=websocket&EIO=3
ERROR
```

**Comment by miguelgrinberg** [comment] 2020-07-17 09:24
Closing as duplicate of #484

**Closed by miguelgrinberg** 2020-07-17 09:24 UTC
Labels: enhancement
