### ISSUE TITLE
Client Randomly Disconnecting

### ISSUE THREAD

**Issue by anon767** [miguelgrinberg/python-socketio#477] opened 2020-05-05 10:30 UTC
Hey Guys,
I recently observe following error when using Python-Socketio as Server with four connected clients.
After some time (about ten minutes) one client disconnects with following log output:
```
INFO:werkzeug:127.0.0.1 - - [05/May/2020 10:23:28] "GET /socket.io/?transport=polling&EIO=3&sid=b91e51d9d9b043ab98293875123a744f&t=1588674208.5054448 HTTP/1.1" 500 -
WARNING:engineio.client:Unexpected status code 500 in server response, aborting
```

I enabled all debugging options that are available (to the best of my knowledge). However it seems that the server is unable to handle the GET Request at this particular time, but I can't see a reason for this. 
Is there any way I can get more information about this 500 Error? 
Actually this seems like an Engineio problem and its maybe related to this issue: https://github.com/miguelgrinberg/python-socketio/issues/475

Thanks in advance :)

**Comment by miguelgrinberg** [comment] 2020-05-05 10:47
I'm closing, since you confirmed the problem is fixed in #475.

**Closed by miguelgrinberg** 2020-05-05 10:47 UTC

**Comment by anon767** [comment] 2020-05-05 10:54
It is a new error occurring although I think this might be connected to #475 due to large messages or high response latency.

Is there a way I can find out why EngineIO is responding with a 500?

**Comment by miguelgrinberg** [comment] 2020-05-05 11:00
Are those two lines from the same logfile? The first is a server-side log, the second is a Socket.IO client log. In the server log you would normally see a stack trace of the error when the response is 500.

**Comment by anon767** [comment] 2020-05-05 11:20
These two lines are taken from the terminal. Server and clients run in their own respective processes, however I started them from within the same shell.
Unfortunately there is no stack trace that is printed.

Mh, strange, the bug disappeared when I set following parameter:
```
manage_session=False
```

**Comment by miguelgrinberg** [comment] 2020-05-05 11:43
Do you have example code you can provide for me to see this error?

**Comment by anon767** [comment] 2020-05-05 11:46
I will try to write a minimal working example to reproduce this bug at the weekend.

**Comment by anon767** [comment] 2020-05-05 18:08
Small update, I managed to get more logs. Although they are not really helpful
```
LOG: HTTP POST request to http://127.0.0.1:5000/socket.io/?transport=polling&EIO=3&sid=7ab1ec126e0040d8ae87259ef997d2c6 failed with error ('Connection aborted.', RemoteDisconnected('Remote end closed connection
without response')).             
LOG: HTTP GET request to http://127.0.0.1:5000/socket.io/?transport=polling&EIO=3&sid=b0b122ac369d4a698c026b2de8470cb8&t=1588698861.2352238 failed with error ('Connection aborted.', RemoteDisconnected('Remote en
d closed connection without response')).
LOG: HTTP GET request to http://127.0.0.1:5000/socket.io/?transport=polling&EIO=3&sid=7ab1ec126e0040d8ae87259ef997d2c6&t=1588699073.8718028 failed with error ('Connection aborted.', RemoteDisconnected('Remote e$
d closed connection without response')).
LOG: Connection refused by the server, aborting
LOG: Waiting for write loop task to end                                                                                  
LOG: Exiting write loop task  
LOG: Connection refused by the server, aborting
LOG: Connection refused by the server, aborting
LOG: Exiting write loop task
LOG: Waiting for write loop task to end
LOG: Waiting for ping loop task to end
```
